### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ar' for key 'PRIMARY'  at install

### ISSUE THREAD

**Issue by wangee** [meedan/checkdesk#2]
Hi!

I've tried to install checkdesk using the installation guided provided in the github repos.
I can't finish the install and I got the error "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ar' for key 'PRIMARY' ".

Please find the following screenshot.   
![capture](https://cloud.githubusercontent.com/assets/7746024/3129794/91b6a9c4-e7ea-11e3-8a09-054aa3b9ff69.PNG)

**Comment by infojunkie** [comment]
@somebaudy, please describe your environment? OS, Web server, MySQL version, PHP version. Thanks!

**Comment by infojunkie** [comment]
Table `languages` has column `language` as primary key, in which the value `ar` is expected to be inserted. I'm looking at conditions where this entry would be inserted more than once.

**Comment by somebaudy** [comment]
here is the technical info on the server : Services:

    CentOS 6.6 64 bits
    Apache 2.2.39
    PHP 5.4.28
    MySQL 5.5.38
    Dovecot/Postfix (Email)
    Bind (DNS)

**Comment by somebaudy** [comment]
@infojunkie @wangee  I absolutely don't need the ar language. Would it be a problem if I delete the ar entry in languages ? Would that solve my problem ?

**Comment by infojunkie** [comment]
Yes, ar language is not essential to operations. Go ahead and try it, and I will confer with @melsawy to see if we can make ar optional during installation.

**Comment by melsawy** [comment]
yes @infojunkie, we can make ar optional.

**Comment by somebaudy** [comment]
It worked. http://crowdchecking.shost.ca/en/ is now live :)

**Comment by infojunkie** [comment]
Great! Can you quickly explain how you resolved the issue?

**Comment by somebaudy** [comment]
I deleted "ar" language in languages table
