### ISSUE TITLE
sql error at the translations stage of the install

### ISSUE THREAD

**Issue by somebaudy** [meedan/checkdesk#3]
I'm stuck at the last part of the install process "Import translations" right after "configure web services" 

I'm getting this SQL error message : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ar' for key 'PRIMARY' 

I seem to remember an installation screen with english and arabic and  I opted for english-only.

No clue on where that duplicate is.

How can i fnd it in phpmyadmin and move to a complete install ?

**Comment by infojunkie** [comment]
@somebaudy I was unfortunately unable to reproduce this error locally. Please head over to #2 and let's continue the conversation there.
